### Задание №1
Массив A состоит из целых положительных чисел длин отрезков. Составьте из трех отрезков такой треугольник, чтобы его периметр был максимально возможным. Если невозможно составить треугольник с положительной площадью функция возвращает 0.

In [1]:
import numpy as np
import numpy.random as rand

In [2]:
def triangleWithMaxPerimeter(ribs):
    perimeter = 0

    for i in range(0,len(ribs)):
        for j in range(i+1,len(ribs)):
            for k in range(j+1,len(ribs)):
                if (ribs[i]+ribs[j]>ribs[k] and ribs[i]+ribs[k]>ribs[j] and ribs[k]+ribs[j]>ribs[i]):
                    if (perimeter<ribs[i]+ribs[j]+ribs[k]):
                        perimeter = ribs[i]+ribs[j]+ribs[k]
                        a = ribs[i]
                        b = ribs[j]
                        c = ribs[k]
    if(perimeter == 0):
        print("bad ribs")
    else:
        print(f'a = {a}, b = {b}, c = {c}')
    return perimeter
array = np.random.randint(1,100,30)
array = np.sort(array)
print(triangleWithMaxPerimeter(array))

a = 97, b = 97, c = 98
292


### Задание №2
Дан массив неотрицательных целых чисел nums. Расположите их в таком порядке, чтобы вместе они образовали максимально возможное число. Замечание: Результат может быть очень большим числом, поэтому представьте его как string, а не integer.

In [3]:
def compareNumbers(a, b):
    first_number = str(a)
    second_number = str(b)

    minLength = len(first_number)
    if len(second_number) < minLength: 
        minLength = len(second_number)

    for digit_index in range(minLength):
        if (int(first_number[digit_index]) < int(second_number[digit_index])):
            return True
        elif int(first_number[digit_index]) == int(second_number[digit_index]):
            if digit_index == minLength-1:
                if len(first_number) < len(second_number):
                    return compareNumbers(int(first_number), int(second_number[minLength : len(second_number)]))
                elif len(first_number) > len(second_number):
                    return compareNumbers(int(first_number[minLength : len(first_number)]), int(second_number))
        else:
            return False

def insertionSort(nums):
        for i in range(1, len(nums)):
            k = i-1
            while k >= 0 and compareNumbers(nums[k], nums[k+1]):
                nums[k], nums[k+1] = nums[k+1], nums[k]
                k-=1

def trimZeros(number):
    for digit_index in range (len(number)):
        if digit_index != len(number)-1:
            if number[digit_index] != '0':
                return number[digit_index:len(number)]
        else:
            return number[digit_index:len(number)]
    return number


def biggestNumber(nums):
    result = ""
    
    insertionSort(nums)

    for i in range(len(nums)):
        result += str(nums[i])

    result = trimZeros(result)

    return result
    
print(biggestNumber([5, 3, 30, 34, 5, 9]))
print(biggestNumber([0,0]))
print(biggestNumber([34323, 3432]))

95534330
0
343234323


### Задание №3
Дана матрица mat размером m * n, значения целочисленные. Напишите функцию, сортирующую каждую диагональ матрицы по возрастанию и возвращающую получившуюся матрицу.

In [4]:
N = 5
M = 6
mtx = np.random.randint(0,100,size=(N,M))

In [5]:
def createLists(mtx):
  to_main_diagnol = []#диагонали ДО главной
  from_main_diagnol = []#диагонали ПОСЛЕ главной
  x, y = 0, 0
  for i in range(M):
      y = i
      x = 0
      temp_list = []
      while (y >= 0 and x < N):
          temp_list.append(mtx[x][y])
          y -= 1
          x += 1 
      to_main_diagnol.append(temp_list)
  for i in range(N-1):
      y = M-1
      x = i+1
      temp_list = []
      while (y >= 0 and x < N):
          temp_list.append(mtx[x][y])
          y -= 1
          x += 1 
      from_main_diagnol.append(temp_list)

  return [to_main_diagnol, from_main_diagnol]

In [6]:
to_main_diagnol, from_main_diagnol = createLists(mtx)
for i in range(len(to_main_diagnol)):
    to_main_diagnol[i]=sorted(to_main_diagnol[i])
for i in range(len(from_main_diagnol)):
    from_main_diagnol[i]=sorted(from_main_diagnol[i])

In [7]:
def createStr(to_main_diagnol, from_main_diagonal, str):
  arr = []
  for i in range(len(to_main_diagnol)):
      if len(to_main_diagnol[i])<str+1:
          continue
      else:
          arr.append(to_main_diagnol[i][str])
  if (0 < str < N):
    ind1 = 0
    ind2 = str-1
    for i in range(str):
      arr.append(from_main_diagnol[ind1][ind2])
      ind1 += 1
      ind2 -= 1

  return arr

In [8]:
print(mtx)
print('___\n')
sorted_matrix = []

for i in range(N):
  sorted_matrix.append(createStr(to_main_diagnol, from_main_diagnol, i))
print(np.array(sorted_matrix))

[[37  8 46 51 18 56]
 [83  3 89 10 47 75]
 [10 78 52  3 19 27]
 [54 23 63 46 64 70]
 [24 27 33 36 63 97]]
___

[[37  8  3 51 10  3]
 [83 10 54 18 27 19]
 [46 78 23 47 33 27]
 [89 24 56 46 36 63]
 [52 63 75 64 70 97]]
